export const charPageOne = 'https://swapi.py4e.com/api/people/?page=1'
export const charPageTwo = 'https://swapi.py4e.com/api/people/?page=2'
export const charPageThree = 'https://swapi.py4e.com/api/people/?page=3'
export const charPageFour = 'https://swapi.py4e.com/api/people/?page=4'
export const charPageFive = 'https://swapi.py4e.com/api/people/?page=5'
export const charPageSix = 'https://swapi.py4e.com/api/people/?page=6'
export const charPageSeven = 'https://swapi.py4e.com/api/people/?page=7'
export const charPageEight = 'https://swapi.py4e.com/api/people/?page=8'
